### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by JeremyDolle** [PolytechLyon/4a-isi3-tp3-2016-2017-groupe-2-petitcuenot-dolle#1]
Il est stipulé, dans le rapport du TP, que toutes les classes "...Personne" doivent comporter une erreur au minimum. Cependant, sur la classe YetAnotherPerson nous n'avons pas d'erreur et nous n'arrivons pas du tout à trouver les tests manquants...

Ensuite pour la question 9, je ne comprend pas bien l’intérêt, j'ai utiliser les différents code coverage inclut dans l'IDE IntelliJ mais je n'ai pas de coloration ou quoi que ce soit de différent...

**Comment by Vlequay** [comment]
Désolé pour la réponse tardive. 
Pour la class YetAnotherPerson ne vous focalisez pas là dessus, vous l'avez remarqué c'est déjà bien.
idem pour la question 9, pas très important, l'outil n'est pas idéal.
Par contre la question 10 est importante et je pense que vous avez compris de travers :) il ne s'agit pas de faire en sorte que la fonction n'ai pas accès aux données, il s'agit de vérifier qu'elle n'essaye pas d'y accéder. Mockito permet ça. Regardez la fin de votre cours ;)

**Comment by JeremyDolle** [comment]
Merci j'ai trouvé, il suffit d'utiliser un verify(moke, never()).getFirstName() 😄

**Comment by Vlequay** [comment]
Yes :) Corrigez le rapport et on pourra fermer tout ça ;)

**Comment by JeremyDolle** [comment]
DONE ✔️
